version: "3.3"

services:
  postgres_db:
    container_name: postgresql
    image: ${POSTGRES_DB_IMAGE}
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    command: postgres -c max_connections=200
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"

volumes:
  postgresdb:
    driver: local
