version: "3.8"

x-redis-common: &redis-common
  image: ${REDIS_IMAGE}
  networks:
    - redis-net
  env_file: .env

services:
  redis-master:
    <<: *redis-common
    container_name: redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis/master.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PORT=${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-replica:
    <<: *redis-common
    volumes:
      - ./config/redis/replica.conf:/usr/local/etc/redis/redis.conf
      - redis-replica-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      redis-master:
        condition: service_healthy
    deploy:
      replicas: ${REDIS_REPLICA_COUNT}
    ports:
      - "${REDIS_REPLICA_START_PORT}-${REDIS_REPLICA_END_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}

  sentinel:
    <<: *redis-common
    volumes:
      - ./config/sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - SENTINEL_PORT=${SENTINEL_PORT}
      - SENTINEL_QUORUM=${SENTINEL_QUORUM}
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
      - SENTINEL_DOWN_AFTER=${SENTINEL_DOWN_AFTER}
      - SENTINEL_FAILOVER_TIMEOUT=${SENTINEL_FAILOVER_TIMEOUT}
      - SENTINEL_PARALLEL_SYNCS=${SENTINEL_PARALLEL_SYNCS}
    deploy:
      replicas: ${SENTINEL_COUNT}
    ports:
      - "${SENTINEL_START_PORT}-${SENTINEL_END_PORT}:${SENTINEL_PORT}"
    depends_on:
      redis-master:
        condition: service_healthy

networks:
  redis-net:
    driver: bridge

volumes:
  redis-master-data:
  redis-replica-data:
